---
title: "R Notebook"
output: html_notebook
---


```{r}
# load packages
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(ggspatial)
library(tidyverse)
library(RColorBrewer)
library(lubridate)
library(plotrix)
library(gridExtra)
library(car)
library(plotly)
library(reshape)
library(grid)
library(lme4)
library(lmerTest)
#library(nlme)
library(reshape)
library(viridis)
library(viridisLite)
library(performance)

set.seed(12345)
```

```{r}
OD_pert_data <- read.csv("./Other_data/OD_data_1.csv", header=T)
OD_pert_tb <- as_tibble(OD_pert_data)
```


```{r}
Blank_value_dat <- OD_pert_tb %>%
  filter (Treatment == "Blank") 

Blank_value <- mean(c(Blank_value_dat$OD))
Blank_value

```

```{r}
OD_pert_tb %>%
  filter (Plate == "pH_salt") %>%
  filter (Treatment == "no_buf") %>%
  mutate(
    Res_type = case_when(
      Resource == "citrate"  ~ "gluconeogenic",
      Resource == "oxoglutarate"  ~ "gluconeogenic",
      Resource == "malate"  ~ "gluconeogenic",
      Resource == "succinate"  ~ "gluconeogenic",
      Resource == "acetate"  ~ "gluconeogenic",
      Resource == "pyruvate"  ~ "gluconeogenic",
      Resource == "proline"  ~ "gluconeogenic",
      Resource == "galacturonate"  ~ "mix",
      Resource == "glucose"  ~ "glycolytic",
      Resource == "fructose"  ~ "glycolytic",
      Resource == "cellobiose"  ~ "glycolytic",
      Resource == "raffinose"  ~ "glycolytic",
      Resource == "starch"  ~ "glycolytic",
      Resource == "sorbitol"  ~ "glycolytic",
      Resource == "cellulose"  ~ "glycolytic",
      Resource == "pectine"  ~ "glycolytic"
      )) %>%
  ggplot(aes(y=OD, x=Day, fill= Resource, group = Resource ))+
  geom_point(shape = 21, size = 3, alpha = .7)+   #, color="brown1"
  geom_line()+
  scale_fill_manual(values = colorRampPalette(brewer.pal(21, "Spectral"))(16))+
  #theme(legend.position="none")+
  #scale_fill_viridis(discrete = FALSE, option="D")+
  labs(x = "Time", y="OD")+
  facet_wrap (~ Res_type)
    
  
```

```{r}
OD_pert_tb %>%
  filter (Plate == "pH_salt") %>%
  filter (Treatment == "salt") %>%
  mutate(
    Res_type = case_when(
      Resource == "citrate"  ~ "gluconeogenic",
      Resource == "oxoglutarate"  ~ "gluconeogenic",
      Resource == "malate"  ~ "gluconeogenic",
      Resource == "succinate"  ~ "gluconeogenic",
      Resource == "acetate"  ~ "gluconeogenic",
      Resource == "pyruvate"  ~ "gluconeogenic",
      Resource == "proline"  ~ "gluconeogenic",
      Resource == "galacturonate"  ~ "mix",
      Resource == "glucose"  ~ "glycolytic",
      Resource == "fructose"  ~ "glycolytic",
      Resource == "cellobiose"  ~ "glycolytic",
      Resource == "raffinose"  ~ "glycolytic",
      Resource == "starch"  ~ "glycolytic",
      Resource == "sorbitol"  ~ "glycolytic",
      Resource == "cellulose"  ~ "glycolytic",
      Resource == "pectine"  ~ "glycolytic"
      )) %>%
  ggplot(aes(y=OD, x=Day, fill= Resource, group = Resource ))+
  geom_point(shape = 21, size = 3, alpha = .7)+   #, color="brown1"
  geom_line()+
  scale_fill_manual(values = colorRampPalette(brewer.pal(21, "Spectral"))(16))+
  #theme(legend.position="none")+
  #scale_fill_viridis(discrete = FALSE, option="D")+
  labs(x = "Time", y="OD")+
  facet_wrap (~ Res_type)
```
```{r}
OD_pert_tb %>%
  filter (Plate == "pH_salt") %>%
  filter (Treatment == "acid") %>%
  mutate(
    Res_type = case_when(
      Resource == "citrate"  ~ "gluconeogenic",
      Resource == "oxoglutarate"  ~ "gluconeogenic",
      Resource == "malate"  ~ "gluconeogenic",
      Resource == "succinate"  ~ "gluconeogenic",
      Resource == "acetate"  ~ "gluconeogenic",
      Resource == "pyruvate"  ~ "gluconeogenic",
      Resource == "proline"  ~ "gluconeogenic",
      Resource == "galacturonate"  ~ "mix",
      Resource == "glucose"  ~ "glycolytic",
      Resource == "fructose"  ~ "glycolytic",
      Resource == "cellobiose"  ~ "glycolytic",
      Resource == "raffinose"  ~ "glycolytic",
      Resource == "starch"  ~ "glycolytic",
      Resource == "sorbitol"  ~ "glycolytic",
      Resource == "cellulose"  ~ "glycolytic",
      Resource == "pectine"  ~ "glycolytic"
      )) %>%
  ggplot(aes(y=OD, x=Day, fill= Resource, group = Resource ))+
  geom_point(shape = 21, size = 3, alpha = .7)+   #, color="brown1"
  geom_line()+
  scale_fill_manual(values = colorRampPalette(brewer.pal(21, "Spectral"))(16))+
  #theme(legend.position="none")+
  #scale_fill_viridis(discrete = FALSE, option="D")+
  labs(x = "Time", y="OD")+
  facet_wrap (~ Res_type)
```

```{r}
OD_pert_tb %>%
  filter (Plate == "pH_salt") %>%
  filter (Treatment == "basic") %>%
  mutate(
    Res_type = case_when(
      Resource == "citrate"  ~ "gluconeogenic",
      Resource == "oxoglutarate"  ~ "gluconeogenic",
      Resource == "malate"  ~ "gluconeogenic",
      Resource == "succinate"  ~ "gluconeogenic",
      Resource == "acetate"  ~ "gluconeogenic",
      Resource == "pyruvate"  ~ "gluconeogenic",
      Resource == "proline"  ~ "gluconeogenic",
      Resource == "galacturonate"  ~ "mix",
      Resource == "glucose"  ~ "glycolytic",
      Resource == "fructose"  ~ "glycolytic",
      Resource == "cellobiose"  ~ "glycolytic",
      Resource == "raffinose"  ~ "glycolytic",
      Resource == "starch"  ~ "glycolytic",
      Resource == "sorbitol"  ~ "glycolytic",
      Resource == "cellulose"  ~ "glycolytic",
      Resource == "pectine"  ~ "glycolytic"
      )) %>%
  ggplot(aes(y=OD, x=Day, fill= Resource, group = Resource ))+
  geom_point(shape = 21, size = 3, alpha = .7)+   #, color="brown1"
  geom_line()+
  scale_fill_manual(values = colorRampPalette(brewer.pal(21, "Spectral"))(16))+
  #theme(legend.position="none")+
  #scale_fill_viridis(discrete = FALSE, option="D")+
  labs(x = "Time", y="OD")+
  facet_wrap (~ Res_type)
```
```{r}
OD_pert_tb %>%
  filter (Plate == "Temp_RT") %>%
  filter (Treatment == "rep1") %>%
  mutate(
    Res_type = case_when(
      Resource == "citrate"  ~ "gluconeogenic",
      Resource == "oxoglutarate"  ~ "gluconeogenic",
      Resource == "malate"  ~ "gluconeogenic",
      Resource == "succinate"  ~ "gluconeogenic",
      Resource == "acetate"  ~ "gluconeogenic",
      Resource == "pyruvate"  ~ "gluconeogenic",
      Resource == "proline"  ~ "gluconeogenic",
      Resource == "galacturonate"  ~ "mix",
      Resource == "glucose"  ~ "glycolytic",
      Resource == "fructose"  ~ "glycolytic",
      Resource == "cellobiose"  ~ "glycolytic",
      Resource == "raffinose"  ~ "glycolytic",
      Resource == "starch"  ~ "glycolytic",
      Resource == "sorbitol"  ~ "glycolytic",
      Resource == "cellulose"  ~ "glycolytic",
      Resource == "pectine"  ~ "glycolytic"
      )) %>%
  ggplot(aes(y=OD, x=Day, fill= Resource, group = Resource ))+
  geom_point(shape = 21, size = 3, alpha = .7)+   #, color="brown1"
  geom_line()+
  scale_fill_manual(values = colorRampPalette(brewer.pal(21, "Spectral"))(16))+
  #theme(legend.position="none")+
  #scale_fill_viridis(discrete = FALSE, option="D")+
  labs(x = "Time", y="OD")+
  facet_wrap (~ Res_type)
```

```{r}
OD_pert_tb %>%
  filter (Plate == "Temp_37") %>%
  filter (Treatment == "rep1") %>%
  mutate(
    Res_type = case_when(
      Resource == "citrate"  ~ "gluconeogenic",
      Resource == "oxoglutarate"  ~ "gluconeogenic",
      Resource == "malate"  ~ "gluconeogenic",
      Resource == "succinate"  ~ "gluconeogenic",
      Resource == "acetate"  ~ "gluconeogenic",
      Resource == "pyruvate"  ~ "gluconeogenic",
      Resource == "proline"  ~ "gluconeogenic",
      Resource == "galacturonate"  ~ "mix",
      Resource == "glucose"  ~ "glycolytic",
      Resource == "fructose"  ~ "glycolytic",
      Resource == "cellobiose"  ~ "glycolytic",
      Resource == "raffinose"  ~ "glycolytic",
      Resource == "starch"  ~ "glycolytic",
      Resource == "sorbitol"  ~ "glycolytic",
      Resource == "cellulose"  ~ "glycolytic",
      Resource == "pectine"  ~ "glycolytic"
      )) %>%
  ggplot(aes(y=OD, x=Day, fill= Resource, group = Resource ))+
  geom_point(shape = 21, size = 3, alpha = .7)+   #, color="brown1"
  geom_line()+
  scale_fill_manual(values = colorRampPalette(brewer.pal(21, "Spectral"))(16))+
  #theme(legend.position="none")+
  #scale_fill_viridis(discrete = FALSE, option="D")+
  labs(x = "Time", y="OD")+
  facet_wrap (~ Res_type)
```
```{r}
OD_pert_tb %>%
  filter (Plate == "Gluco_AB") %>%
  #filter (Treatment == "rep3") %>%
  mutate(
    Res_type = case_when(
      Resource == "citrate"  ~ "gluconeogenic",
      Resource == "oxoglutarate"  ~ "gluconeogenic",
      Resource == "malate"  ~ "gluconeogenic",
      Resource == "succinate"  ~ "gluconeogenic",
      Resource == "acetate"  ~ "gluconeogenic",
      Resource == "pyruvate"  ~ "gluconeogenic",
      Resource == "proline"  ~ "gluconeogenic",
      Resource == "galacturonate"  ~ "mix",
      Resource == "glucose"  ~ "glycolytic",
      Resource == "fructose"  ~ "glycolytic",
      Resource == "cellobiose"  ~ "glycolytic",
      Resource == "raffinose"  ~ "glycolytic",
      Resource == "starch"  ~ "glycolytic",
      Resource == "sorbitol"  ~ "glycolytic",
      Resource == "cellulose"  ~ "glycolytic",
      Resource == "pectine"  ~ "glycolytic"
      )) %>%
  ggplot(aes(y=OD, x=Day, fill= Resource, group = Resource ))+
  geom_point(shape = 21, size = 3, alpha = .7)+   #, color="brown1"
  geom_line()+
  scale_fill_manual(values = colorRampPalette(brewer.pal(21, "Spectral"))(16))+
  #theme(legend.position="none")+
  #scale_fill_viridis(discrete = FALSE, option="D")+
  labs(x = "Time", y="OD")+
  facet_wrap (~ Res_type)
```

