---
title: "R Notebook"
output: html_notebook
---


```{r}
media <- c(50)
rep <- c("a","b","c")
n_media <- length(media)
n_rep <- length(rep)
dat <- df_ALL


for (i in 1:n_media){
  idx_1 <- media[i]
  g = dat[dat$medium==idx_1,]
    for (j in 1:n_rep){
  idx_2 <- rep[j]    
  m = g[g$rep==idx_2,]
  
       if (nrow(m)==0) {
        out_spec_ASV[i,j]= NaN
      } 
      else {
  
  ASV_no0 <- m[m$Abundance>0,]
  ASV_no0$OTU <- factor(ASV_no0$OTU)
  OTUs_50 <- unique(ASV_no0$OTU)

      }
  }
}
  
OTUs_50 


media <- c(51)
rep <- c("a","b","c")
n_media <- length(media)
n_rep <- length(rep)
dat <- df_ALL


for (i in 1:n_media){
  idx_1 <- media[i]
  g = dat[dat$medium==idx_1,]
    for (j in 1:n_rep){
  idx_2 <- rep[j]    
  m = g[g$rep==idx_2,]
  
       if (nrow(m)==0) {
        out_spec_ASV[i,j]= NaN
      } 
      else {
  
  ASV_no0 <- m[m$Abundance>0,]
  ASV_no0$OTU <- factor(ASV_no0$OTU)
  OTUs_51 <- unique(ASV_no0$OTU)

      }
  }
}

OTUs_51 
```


```{r}
df_50 <- df_ALL %>%
  filter(medium == "50") %>%
  filter (Abundance > 0)

ASVs_50 <- unique(df_50$OTU)
ASVs_50

df_51 <- df_ALL %>%
  filter(medium == "51") %>%
  filter (Abundance > 0)

ASVs_51 <- unique(df_51$OTU)
ASVs_51

in_common <- Reduce(intersect, list(ASVs_51,ASVs_50))
in_common
```

ASV1, ASV2, ASV52 --> Pseudomonas spp.
ASV3 Klebsiella Spp.
ASV62 Achromobacter
ASV51 Ensifer
ASV131 Stenotrophomonas
ASV34 Acidovorax


ASV89 Delftia
ASV120 Cryseobacterium
ASV61 Pseudoxanthomonas
ASV131 