---
title: "Water and M9 communities"
output: html_notebook
---


```{r}

ps_day7_noC = ps_day7 %>%
  subset_samples(how_many == "H2O" |
                  how_many == "M9" )
#ps_day7_M9 = subset_samples(ps_day7, how_many == "M9")

ps_day7_noC_RA <-  transform_sample_counts(ps_day7_noC, function(x) {x / sum(x)} )
#ps_day7_M9_RA <-  transform_sample_counts(ps_day7_M9, function(x) {x / sum(x)} )

#Generate prevalence table (number of samples each taxa occurs in) for each taxa.
prevelancedf = apply(X = t(otu_table(ps_day7_noC_RA)),
                     MARGIN = 1,
                     FUN = function(x){sum(x > 0)})
# Add taxonomy and total read counts to this data.frame
prevelancedf = data.frame(Prevalence = prevelancedf,
                          TotalAbundance = taxa_sums(ps_day7_noC_RA),
                          tax_table(ps_day7_noC_RA))

prevalenceThreshold = 0.0001 * nsamples(ps_day7_noC_RA)
prevalenceThreshold  #3.46 (39 families + Others)

Taxa2keep_df <- prevelancedf[prevelancedf$Prevalence >= prevalenceThreshold,]
Families2Keep <- as.vector(unique(Taxa2keep_df$Family))
length(Families2Keep)

Taxa2exclude_df <- prevelancedf[prevelancedf$Prevalence < prevalenceThreshold,]
Families2exclude <- as.vector(unique(Taxa2exclude_df$Family))
length(Families2exclude)

taxa_ps_day7_noC_RA <- tax_table(ps_day7_noC_RA) %>%
  data.frame(stringsAsFactors = FALSE)
taxa_ps_day7_noC_RA$seq <- rownames(taxa_ps_day7_noC_RA)

taxa_ps_day7_noC_RA$Family[!(taxa_ps_day7_noC_RA$Family %in% Families2Keep)] <- "Z_Other"
taxa_ps_day7_noC_RA$Family <- factor(taxa_ps_day7_noC_RA$Family, levels = c(Families2Keep, "Z_Other"))
taxa_ps_day7_noC_RA$otu_id <- seq_len(ncol(otu_table(ps_day7_noC_RA)))
tax_table(ps_day7_noC_RA)[,"Family"] <- as.vector(taxa_ps_day7_noC_RA$Family)

df_day7_noC <- psmelt(ps_day7_noC_RA)
#df_day7_M9 <- psmelt(ps_day7_M9_RA)

```


```{r}
D0 <- estimate_richness(ps_day7_noC,split=TRUE, measures="Observed")
shannon_Silva <- estimate_richness(ps_day7_noC, measures="Shannon")
D1 <- exp(shannon_Silva)
simpson_div_Silva <- estimate_richness(ps_day7_noC, measures="Simpson")
D2 <- estimate_richness(ps_day7_noC, measures="InvSimpson")
ACE <- estimate_richness(ps_day7_noC, measures="ACE")
FaithPD <- estimate_richness_custom(ps_day7_noC, measures="FaithPD")
std_PD <- FaithPD/D0


diversity_noC <- data.frame(sample_data(ps_day7_noC), D0 = D0$Observed, D1 = D1$Shannon, D2 = D2$InvSimpson, shannon = shannon_Silva$Shannon, FaithPD = FaithPD$FaithPD)


#write.csv(diversity_data, "Diversity_data.csv")

diversity_noC_tib <- as_tibble(diversity_noC)
diversity_noC_tib
```



```{r}
families_H2O_fac = factor(tax_table(ps_day7_noC_RA)[, "Family"])
colourCount_fam <- length(unique(families_H2O_fac))


p_H2O <- ggplot(df_day7_noC, aes(ID, Abundance, fill=Family))+
  geom_col(position = position_stack(reverse = TRUE))+
  scale_fill_manual(values = colorRampPalette(brewer.pal(21, "Spectral"))(colourCount_fam))+
  theme_light() +
  theme(legend.position="bottom")+
  facet_wrap(~ how_many)
p_H2O
```
```{r}
df_day7_noC %>%
  filter (Abundance > 0) 
```

```{r}
rrdb_dat <- read_tsv("./Other_data/rrnDB-5.7_pantaxa_stats_RDP.tsv")

```


```{r}
rrdb_dat_genus <- rrdb_dat %>%
  filter (rank == "genus") %>%
  select (name, min, max, median, mean) %>%
  rename (Genus = name, min_CN = min, max_CN = max, median_CN = median, mean_CN = mean)
rrdb_dat_genus

rrdb_dat_fam <- rrdb_dat %>%
  filter (rank == "family") %>%
  select (name, min, max, median, mean) %>%
  rename (Family = name, min_CN_f = min, max_CN_f = max, median_CN_f = median, mean_CN_f = mean)
rrdb_dat_fam

df_day7_noC %>%
  filter (Abundance > 0) %>%
  filter (Kingdom != "NA")%>%
  left_join (rrdb_dat_genus, by = "Genus")%>%
  left_join (rrdb_dat_fam, by = "Family")%>%
  # case_when(
  #   mean_CN = NA ~ mean_CN_f)%>%
  ggplot( aes(x=how_many, y=median_CN, fill=how_many)) +
    geom_violin(width=2.1, size=0.2, alpha = 0.8) +
    scale_fill_brewer() +
    scale_color_brewer() +
    theme_minimal() +
    theme(
      legend.position="none"
    ) +
    #coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("") +
    ylab("Median CN")

```

